"""empty message

Revision ID: 7eef0f0f7451
Revises: 
Create Date: 2018-11-08 20:58:07.010079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eef0f0f7451'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('resortname', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_resortname'), 'post', ['resortname'], unique=False)
    op.create_table('resort',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resortname', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('latitude', sa.Integer(), nullable=True),
    sa.Column('longitude', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resort_resortname'), 'resort', ['resortname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resort_resortname'), table_name='resort')
    op.drop_table('resort')
    op.drop_index(op.f('ix_post_resortname'), table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###
