"""empty message

Revision ID: ff9561bdbf79
Revises: 
Create Date: 2018-11-08 19:48:21.539891

"""
from alembic import op
import sqlalchemy as sa
import sys
sys.path.insert(0, '/../..')
import extract_data


# revision identifiers, used by Alembic.
revision = 'ff9561bdbf79'
down_revision = None
branch_labels = None
depends_on = None



def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table('post',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('body', sa.String(length=140), nullable=True),
	sa.Column('resortname', sa.String(length=64), nullable=True),
	sa.PrimaryKeyConstraint('id')
	)
	op.create_index(op.f('ix_post_resortname'), 'post', ['resortname'], unique=False)
	resort_table = op.create_table('resort',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('resortname', sa.String(length=64), nullable=True),
	sa.Column('state', sa.String(length=2), nullable=True),
	sa.Column('latitude', sa.Integer(), nullable=True),
	sa.Column('longitude', sa.Integer(), nullable=True),
	sa.Column('url', sa.String(length=128), nullable=True),
	sa.PrimaryKeyConstraint('id')
	)
	op.create_index(op.f('ix_resort_resortname'), 'resort', ['resortname'], unique=True)
	# ### end Alembic commands ###

	resort_list = extract_data.extract()

	# Insert into new database
	i = 1
	for state in resort_list:
		statename = state['state']
		for c, resort in enumerate(state['resorts']):
			i += 1
			print(state['geocodes'][c])
			op.bulk_insert(resort_table, [
				{'id':i, 'resortname': resort,
						'state': statename,
						'url': state['urls'][c],
						'latitude': state['geocodes'][c][0],
 						'longitude': state['geocodes'][c][1]}])


def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_index(op.f('ix_resort_resortname'), table_name='resort')
	op.drop_table('resort')
	op.drop_index(op.f('ix_post_resortname'), table_name='post')
	op.drop_table('post')
	# ### end Alembic commands ###
